/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.awt.Color;

public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cerrarsesion = new javax.swing.JButton();
        RegistroClientes = new javax.swing.JButton();
        CalculosTotales = new javax.swing.JButton();
        VecinosCercanos = new javax.swing.JButton();
        RegistroEntregas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menù Principal");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 7, 400, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Calculos Totales ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 210, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Vecinos cercanos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 210, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registro entregas ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 210, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Registro clientes ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 210, -1));

        cerrarsesion.setText("CERRAR");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, -1, -1));

        RegistroClientes.setBackground(new java.awt.Color(204, 204, 204));
        RegistroClientes.setForeground(new java.awt.Color(204, 204, 204));
        RegistroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cliente.png"))); // NOI18N
        RegistroClientes.setBorder(null);
        RegistroClientes.setBorderPainted(false);
        RegistroClientes.setFocusable(false);
        RegistroClientes.setOpaque(true);
        RegistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroClientesActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 200, 140));

        CalculosTotales.setBackground(new java.awt.Color(204, 204, 204));
        CalculosTotales.setForeground(new java.awt.Color(204, 204, 204));
        CalculosTotales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/registros-ordenados.png"))); // NOI18N
        CalculosTotales.setBorderPainted(false);
        CalculosTotales.setFocusPainted(false);
        CalculosTotales.setFocusable(false);
        CalculosTotales.setOpaque(true);
        CalculosTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculosTotalesActionPerformed(evt);
            }
        });
        jPanel1.add(CalculosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 150, 130));

        VecinosCercanos.setBackground(new java.awt.Color(204, 204, 204));
        VecinosCercanos.setForeground(new java.awt.Color(204, 204, 204));
        VecinosCercanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mejoramiento.png"))); // NOI18N
        VecinosCercanos.setToolTipText("");
        VecinosCercanos.setBorderPainted(false);
        VecinosCercanos.setFocusPainted(false);
        VecinosCercanos.setFocusable(false);
        VecinosCercanos.setOpaque(true);
        VecinosCercanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VecinosCercanosActionPerformed(evt);
            }
        });
        jPanel1.add(VecinosCercanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        RegistroEntregas.setBackground(new java.awt.Color(204, 204, 204));
        RegistroEntregas.setForeground(new java.awt.Color(204, 204, 204));
        RegistroEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/costo.png"))); // NOI18N
        RegistroEntregas.setBorderPainted(false);
        RegistroEntregas.setFocusPainted(false);
        RegistroEntregas.setFocusable(false);
        RegistroEntregas.setOpaque(true);
        RegistroEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroEntregasActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        new login ().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void RegistroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroClientesActionPerformed
       // Crear una instancia del nuevo frame
       registroclientes registroFrame = new registroclientes();
       // Hacer visible el nuevo frame
       registroFrame.setVisible(true);
       // Cerrar el frame actual si es necesario
       this.dispose();
    }//GEN-LAST:event_RegistroClientesActionPerformed

    private void CalculosTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculosTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculosTotalesActionPerformed

    private void VecinosCercanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VecinosCercanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VecinosCercanosActionPerformed

    private void RegistroEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroEntregasActionPerformed
       // Crear una instancia del nuevo frame
       registroproduccion registroPFrame = new registroproduccion();
       // Hacer visible el nuevo frame
       registroPFrame.setVisible(true);
       // Cerrar el frame actual si es necesario
       this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_RegistroEntregasActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculosTotales;
    private javax.swing.JButton RegistroClientes;
    private javax.swing.JButton RegistroEntregas;
    private javax.swing.JButton VecinosCercanos;
    private javax.swing.JButton cerrarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
